### ISSUE TITLE
Cleanup Crew

### ISSUE THREAD

**Issue by KingKrabby** [KingKrabby/COMP-55-Resurrection#2]
Organizing all the different classes for each of the functions is important for updating the code.  Some don't need their own scripts and can be combined with others.  This helps alleviate project size and make everything more efficient

**Comment by onzfonz** [comment]
I think I'm going to have you do this but with the added twist of adding some functionality.
For example, have the items or the food that you have be readable from a file.  So this way you can create new food types just by providing images maybe a key and a location or whatever other properties are needed.
This would allow it to be more flexible and also would clean up some of the hardcoding in map_graphics
